[package]
name = "dot_files"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories = "5.0.1"
paris = "1.5"
tempdir = "0.3.7"
tokio = { version = "1", features = ["full"] }
reqwest = "0.11.18"
